name: Frontend CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper git push

    # Set up SSH for Dokku deployment
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.DOKKU_KNOWN_HOSTS }}
        if_key_exists: replace

    # Add Dokku as a remote and push
    - name: Deploy to Dokku
      run: |
        # Set up Git user identity (required for the push)
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Add Dokku as a remote
        git remote add dokku dokku@${{ secrets.DOKKU_HOST }}:gta-frontend
        
        # Push to Dokku
        git push dokku main:master -f
