name: Frontend CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 1.x

    # If you're using Deno for frontend bundling/building as well
    - name: Verify formatting
      run: deno fmt --check

    - name: Run linter
      run: deno lint

    # If you have tests
    - name: Run tests
      run: deno test
      
    # For static analysis of HTML/CSS/JS files (optional)
    - name: HTMLHint
      run: |
        npm install -g htmlhint
        htmlhint ./path/to/html/files
      continue-on-error: true

    - name: StyleLint
      run: |
        npm install -g stylelint stylelint-config-standard
        stylelint "./path/to/css/files/**/*.css"
      continue-on-error: true
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
        restore-keys: |
          ${{ runner.os }}-deno-